spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.200.239:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root#123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: warn
    com.ggl: info
  file:
    name: log/blog-pro.log
server:
  port: 8080
  servlet:
    session:
      timeout: 86400s